# ============================
# URL Shortener — Application Properties
# ============================

# ---- Server ----
server.port=8080

# ---- Application ----
app.base-url=https://cutify.com

# ---- Database (PostgreSQL) ----
spring.datasource.url=jdbc:postgresql://localhost:8606/urlshort
spring.datasource.username=postgres
spring.datasource.password=08062006
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- Logging ----
logging.level.com.urlshortener=DEBUG
logging.level.org.springframework.web=INFO
